# Example of ReplicaSet

---
apiVersion: v1
kind: Pod
metadata:
  name: frontendpod
spec:
  containers:
  - name: nginxpod
    image: nginx
    ports:
    - containerPort: 80
    
...

---
apiVersion: v1
kind: Service
metadata:
  name: frontendservice
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32000
...      
